export const actionTypes = {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  SELECTED_COLOR: "SELECTED_COLOR",
  TODO_TOGGLED: "TODO_TOGGLED",
  ALL_COMPLETED: "ALL_COMPLETED",
  COMPLETED_CLEARED: "COMPLETED_CLEARED",
  SELECTED_ALL_COMPLETED: "SELECTED_ALL_COMPLETED",
}