export enum ActionTypes {
    SELECT_QUIZ = 'SELECT_QUIZ',
    RESET_QUIZ_SELECTION = 'RESET_QUIZ_SELECTION',
    SET_DEVICE_TYPE = 'SET_DEVICE_TYPE',
    SET_USER = 'SET_USER',
    SET_ORDER_DETAILS = 'SET_ORDER_DETAILS',
}