export enum ActionTypes {
    SELECT_QUIZ = 'SELECT_QUIZ',
    RESET_QUIZ_SELECTION = 'RESET_QUIZ_SELECTION',
    SET_DEVICE_TYPE = 'SET_DEVICE_TYPE',
    SET_USER = 'SET_USER',
    SET_ORDER_DETAILS = 'SET_ORDER_DETAILS',
    TOGGLE_CART = 'TOGGLE_CART',
    ADD_ORDER = 'ADD_ORDER',
    CHANGE_ORDER_COUNT = 'CHANGE_ORDER_COUNT',
    REMOVE_ORDER_ITEM = 'REMOVE_ORDER_ITEM',
    ADD_LOCK_SCROLL = 'ADD_LOCK_SCROLL',
    REMOVE_LOCK_SCROLL = 'REMOVE_LOCK_SCROLL'
}